### ISSUE TITLE
file input,output 할때 objectStream사용시 에러가 납니다.

### ISSUE THREAD

**Issue by treetrunks2** [seming/se_project#16]
![eror](https://cloud.githubusercontent.com/assets/19267203/21438009/51edba08-c8ca-11e6-98d2-c375de1bd09e.PNG)
![errror](https://cloud.githubusercontent.com/assets/19267203/21438008/51ed8e8e-c8ca-11e6-91bb-3dc74e7d27f2.PNG)

구현된 메소드를 이용하여 따로 테스트를 해보았는데

objectstream부분에서 에러가 납니다. (try catch로 exception잡은건데 왜 이런건지 노이해)

열심히 구글링을 하다가 너무 잠이와서 여기에 이슈를 올리고 잠에 듭니다.

참고로 테스트는 JUnit으로 안했음. 아직 손도 안댐.ㅜㅜ

**Comment by treetrunks2** [comment]
참고로 코드는 혜인이꺼에서 구현한거랑 별반차이없고 저부근만 에러 나는거 외에는 별다른건 없슴다.

**Comment by treetrunks2** [comment]
@HeaIn @JinYoung00 @seming  해결하였습니다. 멍청하게도 다른함수에서 복붙한 코드를 saveAndExit()에 그대로 사용하였으며, 테스트 파일에선 Note에 implements Serializable을 추가하지도 않았습니다. 저는 멍청이입니다. 절 원망해주십시오.

**Comment by HeaIn** [comment]
zzzzㅋㅋㅋㅋㅋㅋㅋㅋㅋ미안해욬ㅋㅋㅋㅋㅋSerializable 넣어야하는거 말해줬어야했는데 까먹었어요ㅋㅋㅋㅋㅋㅋㅜㅠㅠㅠㅠㅠ

**Comment by JinYoung00** [comment]
난왜 Serializable 추가해도 같은 오류지...
