### ISSUE TITLE
민정이랑 같은오류인디ㅜㅜ 

### ISSUE THREAD

**Issue by JinYoung00** [seming/se_project#17]
![image](https://cloud.githubusercontent.com/assets/16407026/21448431/fcc30540-c925-11e6-9f69-efb341079daa.png)

에러나는 부분이고 파일없으면 추가하는 것도 했는데

![image](https://cloud.githubusercontent.com/assets/16407026/21448434/02b291d2-c926-11e6-8451-23e6f86b4e18.png)

이것도 추가했고 으어어ㅓ

**Comment by HeaIn** [comment]
메소드에 throws IOException이라도 추가해야하나??

**Comment by treetrunks2** [comment]
저거 테스트 돌린 코드도 볼수있음?

**Comment by JinYoung00** [comment]
아 해결했어 , 파일내용에 아무것도 없는데 schedule 객체로 읽어올라니까 형식안맞아서 나는 에러였음
내용읽어올때 scheduleData 가 null 인지 다 확인하도록 해줬어
