### ISSUE TITLE
Java 로 할까요 C 로 할까요 

### ISSUE THREAD

**Issue by JinYoung00** [seming/se_project#3]
@HeaIn @SexyTreeTrunks @seming Java 로 할까요 C 로 할까요 
클래스가 눈에 거슬려서 Java 로 해야할까 싶은..

**Comment by HeaIn** [comment]
클래스 때문에 Java로 해야할 것 같습니다!

**Comment by treetrunks2** [comment]
저도 @HeaIn 의 의견에 동감합니다. @seming 씨는 어떠신지요?

**Comment by seming** [comment]
@SexyTreeTrunks  저도 Java로 해야할 것 같다고 생각합니다!
