### ISSUE TITLE
Account DB

### ISSUE THREAD

**Issue by HeaIn** [seming/se_project#4]
1. 지금 Schedule이랑 Note랑 Phonebook이랑 database가 따로 정의되어있는데 account는 없습니다
배열식으로 정의할까요 아니면 다른 것들처럼 vector로 따로 account를 만들어서 뺄까요?

2. vector로 account DB를 만들 경우 기존에 있는 Account 클래스를 DB용으로 써버리고 login과 signUp을 메인함수 들어있는 Menu클래스에 넣는 것도 좋은 방법인듯합니다.

**Comment by treetrunks2** [comment]
2번 극히 공감합니다.  파라미터로 넘기게 되는 유저 정보(id,passwd)를 최대한 줄이려면 그 방법이 최선인듯 합니다. 2번과 같은 방법으로 ChangeAccount 클래스 또한 Menu클래스에 흡수하는게 나을것 같다는 생각이 듭니다.
