### ISSUE TITLE
DB 같은 아이를 만드면 어떱니까

### ISSUE THREAD

**Issue by JinYoung00** [seming/se_project#5]
어차피 커맨드창인거 DB 를 외부파일로 빼든 어쩌든 클래스를 하나만들어서
마치 DB 같은 역할을 하게 하는거 어떤가요

음.. 거기서 userID, 노트, 스케쥴, 폰 의 벡터들을 다 관리하는거고
select 나 delete 를 가능하게 메소드를 좀 넣자는겁니다....

**Comment by treetrunks2** [comment]
흠 그것은 좀더 생각해 보아야할 문제군요. @seming 씨와 @HeaIn 씨는 어떠신가요?

**Comment by HeaIn** [comment]
저는 벡터 자체가 DB라고 생각하고 있었는데ㅜㅜㅜ 그럼 각각의 manager 클래스에서 delete를 하면 delete 메소드 안에서 디비전용 클래스를 호출한 뒤 거기서 delete 메소드를 또 실행 시키는 건가요??

**Comment by treetrunks2** [comment]
@JinYoung00 씨 @HeaIn 의 질문에 대한 당신의 답변이 궁금합니다.
전체 데이터를 넣을 DB 클래스를 따로 만들게 될경우, 다른 클래스에 있는 메소드에서 데이터가 필요할때마다 DB 클래스를 파라미터로 넣어야 하지 않나요?

**Comment by HeaIn** [comment]
저는 Note, Schedule, Phonebook들을 모아서 배열이나 벡터를 정의하는 것 자체가 데이터베이스라고 생각했었기때문에 굳이 데이터베이스 클래스를 만들지 않아도 괜찮을 것 같습니다.
다만 프로그램을 종료했을 때 데이터가 날아가는걸 방지하기 위해 프로그램 종료할 때 각 정보들은 저장하도록 파일에 빼는건 좋은 방법인듯 합니다.

**Comment by JinYoung00** [comment]
알겠습니다
