### ISSUE TITLE
Vector 의 필요여부

### ISSUE THREAD

**Issue by treetrunks2** [seming/se_project#6]
note, schedule, phonebook 등등 모두 굳이 Vector변수화 해서 사용할 필요가 있을까요?
Vector클래스의 메소드가 추가적으로 필요하지 않는이상 그냥 클래스 배열로 만들어도 될듯합니다.
예를 들면 Note[] noteData = new Note[배열크기] 요런식으로요.

**Comment by HeaIn** [comment]
아 그렇네요 그쪽이 더 다루기 쉬울테니 배열로 바꿀까요? @JinYoung00 @seming 가 괜찮다면 그렇게 바꿔요!

**Comment by JinYoung00** [comment]
동의합니다
