### ISSUE TITLE
데이터 저장에 대하여

### ISSUE THREAD

**Issue by HeaIn** [seming/se_project#7]
회원 정보,  노트 등을 프로그램 종료할 때 소멸자 통해서 특정 파일에 저장하게 할까요? 그리고 생성자에는 파일을 불러오게 하는건 어떤가요?

**Comment by treetrunks2** [comment]
좋은 생각입니다! 각 파일을 불러오고 저장하는 작업은 각 manager class에서 구현하는게 좋을듯 합니다
