### ISSUE TITLE
문서 제출 시간

### ISSUE THREAD

**Issue by HeaIn** [seming/se_project#9]
소웨공 과제 문서 제출 시간을 정해놓고 하는게 좋을 것 같아서요..
대략 9시까지 구글 드라이브로 제출 하는걸로 할까요? 문서 양식 맞추는 데에도 시간이 좀 걸릴 것 같아서요ㅜㅜ

**Comment by JinYoung00** [comment]
ㅇㅇ알겠습니다

**Comment by seming** [comment]
알겠습니다~~
